### ISSUE TITLE
Backup/Restore Version mismatch

### ISSUE THREAD

**Issue by baraapro** [ekondayan/docker-3cx#18]
Hi,

I'm trying to restore a backup from 3CX hosted on a windows. apparently the docker image is not on the latest version. here's the error: 

 The backup version 18.0.9.20 is newer than the PBX version 18.0.8.935. You can restore this backup only with PBX version 18.0.9.20 or newer.

is there a way to resolve this issue?

**Comment by baraapro** [comment]
bump

**Comment by ekondayan** [comment]
These days I will have some time  to update the container to the latest 3CX version.

For your case, you can run the docker container and update to the latest version. Instead of restoring the backup you can start with a dummy config, just to get access to the admin console. From there you can update 3CX and then restore the backup. Never tried it but it should work.
